auto:       true
title: "Yere Düşünce Derneği"
author: "Gökçen Eraslan"
permalink:  /category/:categories/:year-:month-:day/:title
#permalink:  /:year-:month-:day/:title
pygments:   true
paginate:   true
category_title_prefix: "Kategori: "

exclude:
 - _drafts
