pygments: true
permalink: pretty
url: http://blog.yeredusuncedernegi.com
title: Gökçen Eraslan
description: Personal website of Gökçen Eraslan.
author: Gökçen Eraslan
github: gokceneraslan
#email: &#103;&#111;&#107;&#99;&#101;&#110;&#46;&#101;&#114;&#97;&#115;&#108;&#97;&#110;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;
twitter: gokcen
atom: http://feeds.feedburner.com/yeredusuncedernegi

paginate: 5

exclude:
  - README.md

